function ApplyClockWorld()
	SKIN:Bang('!WriteKeyValue Variables MorningWP "#SKINSPATH#\\ClockWorld\\@Resources\\Wallpapers\\Flat\\Morning.jpg" "#@#variables.inc"')
	SKIN:Bang('!WriteKeyValue Variables NoonWP "#SKINSPATH#\\ClockWorld\\@Resources\\Wallpapers\\Flat\\Noon.jpg" "#@#variables.inc"')
	SKIN:Bang('!WriteKeyValue Variables AfternoonWP "#SKINSPATH#\\ClockWorld\\@Resources\\Wallpapers\\Flat\\Afternoon.jpg" "#@#variables.inc"')
	SKIN:Bang('!WriteKeyValue Variables EveningWP "#SKINSPATH#\\ClockWorld\\@Resources\\Wallpapers\\Flat\\Evening.jpg" "#@#variables.inc"')
	SKIN:Bang('!WriteKeyValue Variables NightWP "#SKINSPATH#\\ClockWorld\\@Resources\\Wallpapers\\Flat\\Night.jpg" "#@#variables.inc"')
	SKIN:Bang('!WriteKeyValue Variables MColor "114,86,115" "#@#variables.inc"')
	SKIN:Bang('!WriteKeyValue Variables NColor "72,119,135" "#@#variables.inc"')
	SKIN:Bang('!WriteKeyValue Variables AColor "85,145,107" "#@#variables.inc"')
	SKIN:Bang('!WriteKeyValue Variables EColor "194,86,48" "#@#variables.inc"')
	SKIN:Bang('!WriteKeyValue Variables NTColor "136,51,110" "#@#variables.inc"')
end

function ApplyMeenimal()
	SKIN:Bang('!WriteKeyValue Variables MorningWP "#@#Wallpapers\\Meenimal\\Morning.jpg" "#@#variables.inc"')
	SKIN:Bang('!WriteKeyValue Variables NoonWP "#@#Wallpapers\\Meenimal\\Noon.jpg" "#@#variables.inc"')
	SKIN:Bang('!WriteKeyValue Variables AfternoonWP "#@#Wallpapers\\Meenimal\\Afternoon.jpg" "#@#variables.inc"')
	SKIN:Bang('!WriteKeyValue Variables EveningWP "#@#Wallpapers\\Meenimal\\Evening.jpg" "#@#variables.inc"')
	SKIN:Bang('!WriteKeyValue Variables NightWP "#@#Wallpapers\\Meenimal\\Night.jpg" "#@#variables.inc"')
	SKIN:Bang('!WriteKeyValue Variables MColor "157,101,130" "#@#variables.inc"')
	SKIN:Bang('!WriteKeyValue Variables NColor "76,123,69" "#@#variables.inc"')
	SKIN:Bang('!WriteKeyValue Variables AColor "0,117,124" "#@#variables.inc"')
	SKIN:Bang('!WriteKeyValue Variables EColor "155,82,75" "#@#variables.inc"')
	SKIN:Bang('!WriteKeyValue Variables NTColor "65,125,87" "#@#variables.inc"')
end