function FlatApply()
	SKIN:Bang('!WriteKeyValue Variables MorningWP "#@#Wallpapers\\Flat\\Morning.jpg" "#@#variables.inc"')
	SKIN:Bang('!WriteKeyValue Variables NoonWP "#@#Wallpapers\\Flat\\Noon.jpg" "#@#variables.inc"')
	SKIN:Bang('!WriteKeyValue Variables AfternoonWP "#@#Wallpapers\\Flat\\Afternoon.jpg" "#@#variables.inc"')
	SKIN:Bang('!WriteKeyValue Variables EveningWP "#@#Wallpapers\\Flat\\Evening.jpg" "#@#variables.inc"')
	SKIN:Bang('!WriteKeyValue Variables NightWP "#@#Wallpapers\\Flat\\Night.jpg" "#@#variables.inc"')
	SKIN:Bang('!WriteKeyValue Variables MColor "157,101,130" "#@#variables.inc"')
	SKIN:Bang('!WriteKeyValue Variables NColor "72,119,135" "#@#variables.inc"')
	SKIN:Bang('!WriteKeyValue Variables AColor "85,145,107" "#@#variables.inc"')
	SKIN:Bang('!WriteKeyValue Variables EColor "255,127,80" "#@#variables.inc"')
	SKIN:Bang('!WriteKeyValue Variables NTColor "136,51,110" "#@#variables.inc"')
end